//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner_MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteriner_Calisan
    {
        public int CalisanNo { get; set; }
        public string CalisanAdi { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<int> SubeNo { get; set; }
    }
}
