//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner_MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteriner_Sube
    {
        public int SubeNo { get; set; }
        public string SubeAdi { get; set; }
        public Nullable<int> CalisanSayisi { get; set; }
        public Nullable<int> HizmetSayisi { get; set; }
    }
}
