//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner_MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteriner_Hizmet
    {
        public int HizmetNo { get; set; }
        public string HizmetAdi { get; set; }
        public string HizmetAmaci { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> CalisanNo { get; set; }
    }
}
